### PR TITLE
Fix errors while building tooling-server-configuration due to the addition of the new container adapter

### PR DESCRIPTION
**Pull request by fabiobrz**
Fixes https://github.com/fabiobrz/eap-microprofile-test-suite/issues/26

### CODE REVIEW

**Comment by fabiobrz** [comment]
Hi @spriadka, can you have a look? I noticed an error while building (`tooling-server-configuration`) was unable to decide which container adapter to use (hence adding `*-managed` in the dependencies list) and the I skipped tests for it when `D-ts.bootable` is set because the tooling functionalities are verified against common server instance.
BTW - I got the chance to perform that refactoring we discussed earlier - i.e. move some `Dts.bootable` configuration items up one level.

**Comment by spriadka** [comment]
Hi @fabiobrz, looking good. Could you also add  skipping execution of `initialize-basedirs` execution of `maven-antrun-plugin?`, e.g 
```
<plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>rename-unpacked-jboss-as</id>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <phase>none</phase>
                            </execution>
                            <execution>
                                <id>initialize-basedirs</id>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
```

**Comment by fabiobrz** [comment]
> Hi @fabiobrz, looking good. Could you also add skipping execution of `initialize-basedirs` execution of `maven-antrun-plugin?`, e.g
> 
> ```
> <plugin>
>                         <groupId>org.apache.maven.plugins</groupId>
>                         <artifactId>maven-antrun-plugin</artifactId>
>                         <executions>
>                             <execution>
>                                 <id>rename-unpacked-jboss-as</id>
>                                 <goals>
>                                     <goal>run</goal>
>                                 </goals>
>                                 <phase>none</phase>
>                             </execution>
>                             <execution>
>                                 <id>initialize-basedirs</id>
>                                 <goals>
>                                     <goal>run</goal>
>                                 </goals>
>                                 <phase>none</phase>
>                             </execution>
>                         </executions>
>                     </plugin>
> ```

Hi @spriadka - thanks for your review, done it.

**Comment by spriadka** [comment]
Thanks @fabiobrz, from my point of view, the MR is ready to be merged

**Comment by fabiobrz** [comment]
> Thanks @fabiobrz, from my point of view, the MR is ready to be merged

Thanks @spriadka, merging.

**Pull request merged**
